import scrapy
import json
from datetime import datetime

class RakshSpider(scrapy.Spider):
    name = "raksh_spider"

    def __init__(self, category=None, *args, **kwargs):
        super(RakshSpider, self).__init__(*args, **kwargs)
        self.category = category
        # For Day 3, we target a sandbox site to test logic. 
        # In Phase 2, this URL will be dynamically generated by the LLM.
        self.start_urls = [f"https://quotes.toscrape.com/tag/{category}/"]

    def parse(self, response):
        self.logger.info(f"--- Processing Category: {self.category} ---")
        
        for item in response.css('div.quote'):
            data = {
                'timestamp': datetime.now().isoformat(),
                'category': self.category,
                'source': response.url,
                'raw_text': item.css('span.text::text').get(),
                'author': item.css('small.author::text').get(),
                'tags': item.css('div.tags a.tag::text').getall(),
            }
            yield data

    def closed(self, reason):
        self.logger.info(f"Spider closed: {reason}. Data ready for LLM Council.")